import java.awt.*;
import java.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rainier
 */
public class danososArray extends javax.swing.JFrame {
    
    private ArrayList<Integer> dataList = new ArrayList<>();
    
    private int inputData(){
        return Integer.parseInt(txtInputData.getText());
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(danososArray.class.getName());

    /**
     * Creates new form danososArray
     */
    public danososArray() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtOutputArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblArrayList = new javax.swing.JLabel();
        lblEnterData = new javax.swing.JLabel();
        txtInputData = new javax.swing.JTextField();
        btnAddData = new javax.swing.JButton();
        btnAccessData = new javax.swing.JButton();
        btnChangeData = new javax.swing.JButton();
        btnRemoveData = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        txtOutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));

        lblArrayList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArrayList.setForeground(new java.awt.Color(240, 240, 240));
        lblArrayList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArrayList.setText("ARRAY LIST");

        lblEnterData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnterData.setForeground(new java.awt.Color(170, 170, 170));
        lblEnterData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnterData.setText("Enter Data:");

        txtInputData.setBackground(new java.awt.Color(17, 17, 17));
        txtInputData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInputData.setForeground(new java.awt.Color(224, 224, 224));
        txtInputData.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAddData.setBackground(new java.awt.Color(44, 44, 44));
        btnAddData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddData.setForeground(new java.awt.Color(224, 224, 224));
        btnAddData.setText("Add");
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });

        btnAccessData.setBackground(new java.awt.Color(44, 44, 44));
        btnAccessData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAccessData.setForeground(new java.awt.Color(224, 224, 224));
        btnAccessData.setText("Access");
        btnAccessData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessDataActionPerformed(evt);
            }
        });

        btnChangeData.setBackground(new java.awt.Color(44, 44, 44));
        btnChangeData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangeData.setForeground(new java.awt.Color(224, 224, 224));
        btnChangeData.setText("Change");
        btnChangeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDataActionPerformed(evt);
            }
        });

        btnRemoveData.setBackground(new java.awt.Color(56, 48, 48));
        btnRemoveData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemoveData.setForeground(new java.awt.Color(224, 144, 144));
        btnRemoveData.setText("Remove");
        btnRemoveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDataActionPerformed(evt);
            }
        });

        lblOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(170, 170, 170));
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOutput.setText("Output:");

        txtOutputArea.setBackground(new java.awt.Color(17, 17, 17));
        txtOutputArea.setColumns(20);
        txtOutputArea.setForeground(new java.awt.Color(187, 187, 187));
        txtOutputArea.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutputArea)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblArrayList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEnterData)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtInputData))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAccessData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnChangeData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRemoveData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArrayList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInputData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccessData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutputArea, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAccessDataActionPerformed

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddDataActionPerformed

    private void btnRemoveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRemoveDataActionPerformed

    private void btnChangeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnChangeDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new danososArray().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessData;
    private javax.swing.JButton btnAddData;
    private javax.swing.JButton btnChangeData;
    private javax.swing.JButton btnRemoveData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArrayList;
    private javax.swing.JLabel lblEnterData;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JTextField txtInputData;
    private javax.swing.JTextArea txtOutputArea;
    // End of variables declaration//GEN-END:variables
}
